Node:
    type: interface
    config:
        fields:
            id:
                type: "ID!"


RelayConnection:
    type: relay-connection
    config:
        connectionFields:
            pageSize:
                type: Int
            pageCount:
                type: Int
            totalCount:
                type: Int
