services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Processor\BulkDelete\BulkDeleteProcessor:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'bulk_delete'
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'

    # intialize

    # security

    # delete
    Videni\Bundle\RestBundle\Processor\BulkDelete\BulkDeleteResource:
        tags:
            - { name: videni_rest.processor, action: bulk_delete, group: delete, priority: 10 }
