services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\BulkDelete\BulkDeleteProcessor:
        public: false
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'bulk_delete'
            - '@App\Bundle\RestBundle\Metadata\Resource\Factory\ResourceMetadataFactory'

    # intialize

    # security

    # delete
    App\Bundle\RestBundle\Processor\BulkDelete\BulkDeleteResource:
        tags:
            - { name: app_rest.processor, action: bulk_delete, group: delete, priority: 10 }
