services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Processor\Create\CreateProcessor:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'create'
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'
    # intialize
    Videni\Bundle\RestBundle\Processor\Create\CreateResource:
        arguments: ['@service_container', '@Videni\Bundle\RestBundle\Factory\ParametersParserInterface']
        tags:
            - { name: videni_rest.processor, action: create, group: initialize, priority: 10 }

    # security

    # deserialize


    # validate

    # save
