services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\Create\CreateProcessor:
        public: false
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'create'
            - '@App\Bundle\RestBundle\Metadata\Resource\Factory\ResourceMetadataFactory'

    App\Bundle\RestBundle\Processor\Create\CreateResource:
        arguments: ['@service_container', '@App\Bundle\RestBundle\Factory\ParametersParserInterface']
        tags:
            - { name: app_rest.processor, action: create, group: initialize, priority: 10 }

    App\Bundle\RestBundle\Processor\DeserializationProcessor:
        arguments: ['@jms_serializer']
        tags:
            - { name: app_rest.processor, action: create, group: deserialize, priority: 10 }

    App\Bundle\RestBundle\Processor\ValidationProcessor:
        tags:
            - { name: app_rest.processor, action: create, group: validate, priority: 10 }

    App\Bundle\RestBundle\Processor\Create\SaveResource:
        tags:
            - { name: app_rest.processor, action: create, group: save, priority: 10 }

    App\Bundle\RestBundle\Validator\Validator:
        arguments: ['@validator', '@service_container']

    App\Bundle\RestBundle\Validator\ValidatorInterface: '@App\Bundle\RestBundle\Validator\Validator'

    App\Bundle\RestBundle\Processor\PermissionProcessor:
        tags:
            - { name: app_rest.processor, action: create, group: security, priority: 10 }
