services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Processor\Delete\DeleteProcessor:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'delete'
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'

    # intialize

    # security

    # delete
    Videni\Bundle\RestBundle\Processor\Delete\DeleteResource:
        tags:
            - { name: videni_rest.processor, action: delete, group: delete, priority: 10 }
