services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\Index\IndexProcessor:
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'index'
            - '@App\Bundle\RestBundle\Metadata\Resource\Factory\ResourceMetadataFactory'
    # intialize


    # security

    # deserialize


    # validate

    # save
