services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\Index\IndexProcessor:
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'index'
            - '@App\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'
    # intialize


    # security

    # deserialize


    # validate

    # save
