services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\Update\UpdateProcessor:
        public: false
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'update'
            - '@App\Bundle\RestBundle\Metadata\Resource\Factory\ResourceMetadataFactory'

    # initialize

    # security

    # deserialize

    # validate

    # save
