services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Processor\Update\UpdateProcessor:
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'update'
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'

    # initialize

    # security

    # deserialize

    # validate

    # save
