services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Processor\View\ViewProcessor:
        public: false
        arguments:
            - '@App\Bundle\RestBundle\Processor\OptimizedProcessorBag'
            - 'view'
            - '@App\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'

    # initialize
