services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Config\Resource\ResourceProvider:
        public: true
        arguments:
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceLoader'
            - '%videni_rest.resource_config%'

    Videni\Bundle\RestBundle\Config\Resource\ResourceLoader: ~

