services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider:
        public: true
        arguments:
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigLoader'
            - '%videni_rest.resource_config%'

    Videni\Bundle\RestBundle\Config\Paginator\PaginatorConfigLoader: ~

    Videni\Bundle\RestBundle\Config\Form\FormConfigLoader: ~

    Videni\Bundle\RestBundle\Config\Resource\ResourceConfigLoader:
        arguments:
            - '@Videni\Bundle\RestBundle\Config\Form\FormConfigLoader'
            - '@Videni\Bundle\RestBundle\Config\Paginator\PaginatorConfigLoader'
