services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Context\ResourceContextStorage: ~

    Videni\Bundle\RestBundle\Provider\ResourceProvider\CollectionResourceProvider: ~

    Videni\Bundle\RestBundle\Provider\ResourceProvider\SingleResourceProvider:
        arguments:
            - '@service_container'
            - '@Videni\Bundle\RestBundle\Factory\ParametersParserInterface'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@=parameter("videni_rest.bundle_config")["application_name"]'

    Videni\Bundle\RestBundle\Factory\NewResourceFactory: ~

    Videni\Bundle\RestBundle\EventListener\DataPersister: ~

    Negotiation\Negotiator: ~

# kernel.request event
    Videni\Bundle\RestBundle\EventListener\ResourceContextListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 8 }

    Videni\Bundle\RestBundle\EventListener\FormatListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 7 }

    Videni\Bundle\RestBundle\EventListener\ResourceListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 4 }

    Videni\Bundle\RestBundle\EventListener\FormListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2 }

# kernel.view event
    Videni\Bundle\RestBundle\EventListener\WriteListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 32 }

    Videni\Bundle\RestBundle\EventListener\SerializeListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 16 }

    Videni\Bundle\RestBundle\EventListener\RespondListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 8 }

# kernel.exception event
    Videni\Bundle\RestBundle\Validator\EventListener\ValidationExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException'}
