services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Form\FormHelper:
        public: false
        arguments:
            - '@form.factory'
            - '@Videni\Bundle\RestBundle\Form\FormPropertyAccessor'
            - '@service_container'

    Videni\Bundle\RestBundle\Form\FormPropertyAccessor:
        public: false
        arguments:
            - '@form.property_accessor'

    Videni\Bundle\RestBundle\Form\FormExtensionState: ~

    Videni\Bundle\RestBundle\Form\Extension\SwitchableDependencyInjectionExtension:
        arguments:
            - '@service_container'

    Videni\Bundle\RestBundle\Form\FormExtension:
        arguments:
            - '@service_container'
            - [] # All services with tag "videni_rest.form.type" are inserted here by Videni\Bundle\RestBundle\DependencyInjection\Compiler\FormCompilerPass
            - [] # All services with tag "videni_rest.form.type_extension" are inserted here by Videni\Bundle\RestBundle\DependencyInjection\Compiler\FormCompilerPass
            - [] # All services with tag "videni_rest.form.type_guesser" are inserted here by Videni\Bundle\RestBundle\DependencyInjection\Compiler\FormCompilerPass

    Videni\Bundle\RestBundle\Form\Extension\ValidationExtension:
        arguments:
            - '@validator'
        tags:
            - { name: videni_rest.form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Videni\Bundle\RestBundle\Form\Extension\DateTimeExtension:
        tags:
            - { name: videni_rest.form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }

    Videni\Bundle\RestBundle\Form\Extension\CustomizeFormDataExtension:
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\CustomizeFormData\CustomizeFormDataProcessor'
            - '@Videni\Bundle\RestBundle\Processor\CustomizeFormData\CustomizeFormDataHandler'
        tags:
            - { name: videni_rest.form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Videni\Bundle\RestBundle\Processor\CustomizeFormData\CustomizeFormDataHandler:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Processor\CustomizeFormData\CustomizeFormDataProcessor'

    Videni\Bundle\RestBundle\Form\FormValidationHandler: ~


    Videni\Bundle\RestBundle\Form\Guesser\MetadataTypeGuesser:
        arguments:
            - [] # Data type mappings are inserted here by Videni\Bundle\RestBundle\DependencyInjection\Compiler\FormCompilerPass
            - '@Videni\Bundle\RestBundle\Util\DoctrineHelper'
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'
        tags:
            - { name: videni_rest.form.type_guesser, priority: 10 }

    # Videni\Bundle\RestBundle\Form\Type\NestedAssociationType:
    #     arguments:
    #         - '@oro_api.entity_loader'
    #     tags:
    #         - { name: videni_rest.form.type, alias: Videni\Bundle\RestBundle\Form\Type\NestedAssociationType }

    Videni\Bundle\RestBundle\Form\Type\ObjectType:
        tags:
            - { name: videni_rest.form.type, alias: Videni\Bundle\RestBundle\Form\Type\ObjectType }

    Videni\Bundle\RestBundle\Form\Type\CompoundObjectType:
        tags:
            - { name: videni_rest.form.type, alias: Videni\Bundle\RestBundle\Form\Type\CompoundObjectType }

