services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Routing\ResourceRouteLoader:
        arguments:
            - '@Videni\Bundle\RestBundle\Config\Resource\ResourceConfigProvider'
            - '@Videni\Bundle\RestBundle\Routing\PathResolver\OperationPathResolver'
            - 'Videni\Bundle\RestBundle\Controller\ResourceController'
        tags: [ 'routing.loader' ]

    Videni\Bundle\RestBundle\Routing\PathResolver\OperationPathResolver:
        arguments:
            - '@Videni\Bundle\RestBundle\Operation\UnderscorePathSegmentNameGenerator'

    Videni\Bundle\RestBundle\Operation\UnderscorePathSegmentNameGenerator: ~

