services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Security\ResourceAccessChecker:
        arguments:
            - '@Videni\Bundle\RestBundle\Security\ExpressionLanguage'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@security.authentication.trust_resolver'
            - '@?security.role_hierarchy'

    Videni\Bundle\RestBundle\Security\ResourceAccessCheckerInterface: '@Videni\Bundle\RestBundle\Security\ResourceAccessChecker'

    Videni\Bundle\RestBundle\Security\ExpressionLanguage: ~
