services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Serializer\Handler\ConstraintViolationListHandler:
        tags:
            - { name: 'jms_serializer.subscribing_handler' }
