services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Serializer\Handler\FormErrorNormalizer:
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    Videni\Bundle\RestBundle\Serializer\Handler\FormDataNormalizer:
        tags:
            - { name: 'jms_serializer.subscribing_handler' }
