services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\RestBundle\Serializer\SerializerContextBuilder: ~

    jms_serializer.object_constructor: '@App\Bundle\RestBundle\Serializer\ObjectConstructor'

    App\Bundle\RestBundle\Serializer\ObjectConstructor:
        arguments: ['@jms_serializer.doctrine_object_constructor']
