services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    jms_serializer.object_constructor: '@Videni\Bundle\RestBundle\Serializer\ObjectConstructor'

    Videni\Bundle\RestBundle\Serializer\ObjectConstructor:
        arguments: ['@jms_serializer.doctrine_object_constructor']
