services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\RestBundle\Util\CriteriaConnector:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Util\CriteriaNormalizer'
            - '@Videni\Bundle\RestBundle\Util\CriteriaPlaceholdersResolver'
            - '@Videni\Bundle\RestBundle\Collection\QueryExpressionVisitorFactory'
            - '@Videni\Bundle\RestBundle\Util\EntityClassResolver'

    Videni\Bundle\RestBundle\Util\CriteriaNormalizer:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Util\DoctrineHelper'
            - '@Videni\Bundle\RestBundle\Util\RequireJoinsFieldVisitorFactory'
            - '@Videni\Bundle\RestBundle\Util\OptimizeJoinsFieldVisitorFactory'

    Videni\Bundle\RestBundle\Util\CriteriaPlaceholdersResolver:
        class: Videni\Bundle\RestBundle\Util\CriteriaPlaceholdersResolver
        public: false

    Videni\Bundle\RestBundle\Util\RequireJoinsFieldVisitorFactory:
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Util\RequireJoinsDecisionMaker'

    Videni\Bundle\RestBundle\Util\RequireJoinsDecisionMaker:
        class: Videni\Bundle\RestBundle\Util\RequireJoinsDecisionMaker
        public: false

    Videni\Bundle\RestBundle\Util\OptimizeJoinsFieldVisitorFactory:
        class: Videni\Bundle\RestBundle\Util\OptimizeJoinsFieldVisitorFactory
        public: false
        arguments:
            - '@Videni\Bundle\RestBundle\Util\OptimizeJoinsDecisionMaker'

    Videni\Bundle\RestBundle\Util\OptimizeJoinsDecisionMaker:
        class: Videni\Bundle\RestBundle\Util\OptimizeJoinsDecisionMaker
        public: false

    Videni\Bundle\RestBundle\Util\DoctrineHelper: ~

    Videni\Bundle\RestBundle\Util\EntityClassResolver: ~
