Hateoas\Representation\PaginatedRepresentation:
    exclusion_policy: ALL
    xml_root_name: collection
    accessor_order: custom
    custom_accessor_order: [page, limit, pages, total]
    properties:
        page:
            type: integer
            xml_attribute: true
        pages:
            type: integer
            xml_attribute: true
    relations:
        -   rel: first
            href:
                route: expr(object.getRoute())
                parameters: expr(object.getParameters(1))
                absolute: expr(object.isAbsolute())
        -   rel: last
            href:
                route: expr(object.getRoute())
                parameters: expr(object.getParameters(object.getPages()))
                absolute: expr(object.isAbsolute())
            exclusion:
                exclude_if: expr(object.getPages() === null)
        -   rel: next
            href:
                route: expr(object.getRoute())
                parameters: expr(object.getParameters(object.getPage() + 1))
                absolute: expr(object.isAbsolute())
            exclusion:
                exclude_if: expr(object.getPages() !== null && (object.getPage() + 1) > object.getPages())
        -   rel: previous
            href:
                route: expr(object.getRoute())
                parameters: expr(object.getParameters(object.getPage() - 1))
                absolute: expr(object.isAbsolute())
            exclusion:
                exclude_if: expr((object.getPage() - 1) < 1)
    relation_providers: ['videni_rest.grid_relation_provider:getRelations']



